import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { MessageCircle, Plus, Send, StickyNote, Phone, ShieldCheck, RefreshCw } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useWorkspace } from "@/hooks/useWorkspace";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

type NumberRow = { id: string; workspace_id: string; phone_number_id: string; display_phone_number: string | null; verified_name: string | null; status: string; last_error: string | null; last_webhook_at: string | null };
type Conversation = { id: string; whatsapp_number_id: string; contact_name: string | null; contact_phone: string | null; status: string; summary: string | null; unread_count: number; last_message_at: string | null };
type Message = { id: string; direction: "inbound" | "outbound"; body: string | null; sent_at: string; status: string };

export default function WhatsApp() {
  const { data: workspace } = useWorkspace();
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const workspaceId = workspace?.id;
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showConnect, setShowConnect] = useState(false);
  const [message, setMessage] = useState("");
  const [note, setNote] = useState("");
  const [form, setForm] = useState({ wabaId: "", phoneNumberId: "", accessToken: "" });
  const numbers = useQuery({ queryKey: ["whatsapp_numbers", workspaceId], enabled: !!workspaceId, queryFn: async () => { const { data, error } = await (supabase as any).from("whatsapp_numbers").select("id,workspace_id,phone_number_id,display_phone_number,verified_name,status,last_error,last_webhook_at").eq("workspace_id", workspaceId).order("created_at"); if (error) throw error; return (data || []) as NumberRow[]; }, staleTime: 60_000, refetchOnWindowFocus: true });
  const conversations = useQuery({ queryKey: ["whatsapp_conversations", workspaceId], enabled: !!workspaceId, queryFn: async () => { const { data, error } = await (supabase as any).from("whatsapp_conversations").select("id,whatsapp_number_id,contact_name,contact_phone,status,summary,unread_count,last_message_at").eq("workspace_id", workspaceId).order("last_message_at", { ascending: false }); if (error) throw error; return (data || []) as Conversation[]; }, staleTime: 30_000, refetchOnWindowFocus: true });
  const selected = conversations.data?.find((item) => item.id === selectedId) || conversations.data?.[0];
  useEffect(() => { if (!selectedId && conversations.data?.[0]) setSelectedId(conversations.data[0].id); }, [conversations.data, selectedId]);
  const messages = useQuery({ queryKey: ["whatsapp_messages", selected?.id], enabled: !!selected?.id, queryFn: async () => { const { data, error } = await (supabase as any).from("whatsapp_messages").select("id,direction,body,sent_at,status").eq("conversation_id", selected!.id).order("sent_at"); if (error) throw error; return (data || []) as Message[]; }, staleTime: 10_000, refetchOnWindowFocus: true });
  const notes = useQuery({ queryKey: ["whatsapp_notes", selected?.id], enabled: !!selected?.id, queryFn: async () => { const { data, error } = await (supabase as any).from("whatsapp_conversation_notes").select("id,body,created_at").eq("conversation_id", selected!.id).order("created_at", { ascending: false }); if (error) throw error; return data || []; } });
  useEffect(() => { if (!workspaceId) return; const channel = supabase.channel(`whatsapp-live-${workspaceId}`).on("postgres_changes", { event: "*", schema: "public", table: "whatsapp_conversations", filter: `workspace_id=eq.${workspaceId}` }, () => { void conversations.refetch(); }).on("postgres_changes", { event: "*", schema: "public", table: "whatsapp_messages", filter: `workspace_id=eq.${workspaceId}` }, () => { void messages.refetch(); void conversations.refetch(); }).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [workspaceId]);
  const connect = useMutation({ mutationFn: async () => { const { data, error } = await supabase.functions.invoke("whatsapp-connect", { body: { workspace_id: workspaceId, waba_id: form.wabaId, phone_number_id: form.phoneNumberId, access_token: form.accessToken } }); if (error || data?.error) throw new Error(error?.message || data?.error); return data; }, onSuccess: () => { setForm({ wabaId: "", phoneNumberId: "", accessToken: "" }); setShowConnect(false); void numbers.refetch(); } });
  const send = useMutation({ mutationFn: async () => { const { data, error } = await supabase.functions.invoke("whatsapp-send", { body: { conversation_id: selected?.id, text: message } }); if (error || data?.error) throw new Error(error?.message || data?.error); }, onSuccess: () => { setMessage(""); void messages.refetch(); } });
  const saveNote = useMutation({ mutationFn: async () => { const { error } = await (supabase as any).from("whatsapp_conversation_notes").insert({ workspace_id: workspaceId, conversation_id: selected?.id, user_id: user?.id, body: note.trim() }); if (error) throw error; }, onSuccess: () => { setNote(""); void notes.refetch(); } });
  const selectedNumber = useMemo(() => numbers.data?.find((item) => item.id === selected?.whatsapp_number_id), [numbers.data, selected]);
  return <div className="mx-auto flex h-full min-h-0 w-full max-w-[1600px] flex-col gap-4 p-4 lg:p-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-primary">WhatsApp Cloud API</p><h1 className="mt-1 text-2xl font-black">Conversas</h1><p className="mt-1 text-sm text-muted-foreground">Conecte vários números oficiais e acompanhe as conversas recebidas pelo webhook da Meta.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => { void numbers.refetch(); void conversations.refetch(); }}><RefreshCw className="mr-2 h-4 w-4" />Atualizar</Button><Button onClick={() => setShowConnect((value) => !value)}><Plus className="mr-2 h-4 w-4" />Conectar número</Button></div></header>
    {showConnect && <section className="gd-panel grid gap-3 p-4 md:grid-cols-4"><Input placeholder="WABA ID" value={form.wabaId} onChange={(e) => setForm({ ...form, wabaId: e.target.value })} /><Input placeholder="Phone Number ID" value={form.phoneNumberId} onChange={(e) => setForm({ ...form, phoneNumberId: e.target.value })} /><Input type="password" placeholder="Token permanente da Cloud API" value={form.accessToken} onChange={(e) => setForm({ ...form, accessToken: e.target.value })} /><Button onClick={() => connect.mutate()} disabled={connect.isPending || !workspaceId}>{connect.isPending ? "Validando na Meta…" : "Validar e conectar"}</Button>{connect.error && <p className="text-xs text-destructive md:col-span-4">{(connect.error as Error).message}</p>}<p className="text-[11px] text-muted-foreground md:col-span-4"><ShieldCheck className="mr-1 inline h-3.5 w-3.5" />Use um token oficial com permissões <code>whatsapp_business_management</code> e <code>whatsapp_business_messaging</code>. O token não é exibido nas consultas do navegador.</p></section>}
    <section className="grid min-h-0 flex-1 gap-4 xl:grid-cols-[260px_300px_minmax(0,1fr)_300px]">
      <aside className="gd-panel min-h-0 overflow-y-auto p-3"><h2 className="mb-3 text-xs font-black uppercase tracking-wider">Números conectados</h2>{numbers.data?.map((item) => <div key={item.id} className="mb-2 rounded-xl border border-border p-3"><div className="flex items-center gap-2"><Phone className="h-4 w-4 text-primary" /><div className="min-w-0"><b className="block truncate text-sm">{item.verified_name || item.display_phone_number || item.phone_number_id}</b><small className="text-muted-foreground">{item.display_phone_number || "Número oficial"}</small></div></div><span className={cn("mt-2 inline-flex rounded-full px-2 py-0.5 text-[10px] font-bold", item.status === "connected" ? "bg-emerald-500/15 text-emerald-500" : "bg-rose-500/15 text-rose-500")}>{item.status === "connected" ? "Conectado" : "Erro"}</span>{item.last_error && <p className="mt-2 text-[10px] text-destructive">{item.last_error}</p>}</div>)}{!numbers.data?.length && <p className="text-xs text-muted-foreground">Nenhum número conectado.</p>}</aside>
      <aside className="gd-panel min-h-0 overflow-y-auto p-2"><h2 className="px-2 py-2 text-xs font-black uppercase tracking-wider">Conversas</h2>{conversations.data?.map((item) => <button key={item.id} type="button" onClick={() => setSelectedId(item.id)} className={cn("mb-1 w-full rounded-xl p-3 text-left transition", selected?.id === item.id ? "bg-primary/15" : "hover:bg-muted")}><div className="flex items-center justify-between gap-2"><b className="truncate text-sm">{item.contact_name || item.contact_phone || "Contato WhatsApp"}</b>{item.unread_count > 0 && <span className="rounded-full bg-primary px-2 py-0.5 text-[10px] font-bold text-primary-foreground">{item.unread_count}</span>}</div><p className="mt-1 truncate text-[11px] text-muted-foreground">{item.summary || "Nova conversa recebida"}</p></button>)}{!conversations.data?.length && <p className="p-3 text-xs text-muted-foreground">As mensagens recebidas aparecerão aqui.</p>}</aside>
      <main className="gd-panel flex min-h-0 flex-col overflow-hidden"><header className="border-b border-border p-4"><div className="flex items-center gap-2"><MessageCircle className="h-5 w-5 text-primary" /><div><h2 className="font-black">{selected?.contact_name || selected?.contact_phone || "Selecione uma conversa"}</h2><p className="text-[11px] text-muted-foreground">{selectedNumber?.display_phone_number || "WhatsApp oficial"}</p></div></div></header><div className="min-h-0 flex-1 space-y-3 overflow-y-auto bg-muted/15 p-4">{messages.data?.map((item) => <div key={item.id} className={cn("flex", item.direction === "outbound" ? "justify-end" : "justify-start")}><div className={cn("max-w-[78%] rounded-2xl px-3 py-2 text-sm", item.direction === "outbound" ? "bg-primary text-primary-foreground" : "bg-card border border-border")}><p>{item.body || "[Mensagem sem texto]"}</p><small className="mt-1 block text-[9px] opacity-60">{new Date(item.sent_at).toLocaleString("pt-BR")}</small></div></div>)}{!messages.data?.length && <p className="py-10 text-center text-xs text-muted-foreground">Nenhuma mensagem nesta conversa.</p>}</div><form className="flex gap-2 border-t border-border p-3" onSubmit={(e) => { e.preventDefault(); if (message.trim()) send.mutate(); }}><Input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Digite uma mensagem..." disabled={!selected || send.isPending} /><Button type="submit" size="icon" disabled={!selected || !message.trim() || send.isPending}><Send className="h-4 w-4" /></Button></form></main>
      <aside className="gd-panel min-h-0 overflow-y-auto p-4"><div className="flex items-center gap-2"><StickyNote className="h-4 w-4 text-primary" /><h2 className="font-black">Resumo e anotações</h2></div><p className="mt-3 text-xs text-muted-foreground">Resumo da conversa: {selected?.summary || "Ainda não há resumo gerado."}</p><Textarea className="mt-4 min-h-24" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Adicionar anotação interna..." disabled={!selected} /><Button className="mt-2 w-full" variant="outline" onClick={() => saveNote.mutate()} disabled={!selected || !note.trim() || saveNote.isPending}>Salvar anotação</Button><div className="mt-5 space-y-3">{notes.data?.map((item: any) => <article key={item.id} className="rounded-lg border border-border p-3"><p className="text-xs">{item.body}</p><small className="mt-2 block text-[10px] text-muted-foreground">{new Date(item.created_at).toLocaleString("pt-BR")}</small></article>)}</div></aside>
    </section>
  </div>;
}
