import { useMemo, useState } from "react";
import { Check, ChevronDown, Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

type AccountOption = { id: string; name: string };

export function AccountMultiSelect({ accounts, selectedIds, onChange, className, popoverClassName, emptyLabel = "Todas as contas", singularLabel = "conta", pluralLabel = "contas", ariaLabel = "Selecionar contas de anúncio", searchPlaceholder = "Pesquisar conta…" }: { accounts: AccountOption[]; selectedIds: string[]; onChange: (ids: string[]) => void; className?: string; popoverClassName?: string; emptyLabel?: string; singularLabel?: string; pluralLabel?: string; ariaLabel?: string; searchPlaceholder?: string }) {
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return query ? accounts.filter((account) => account.name.toLowerCase().includes(query) || account.id.includes(query)) : accounts; }, [accounts, search]);
  const label = selectedIds.length === 0 ? emptyLabel : selectedIds.length === 1 ? accounts.find((account) => account.id === selectedIds[0])?.name ?? `1 ${singularLabel}` : `${selectedIds.length} ${pluralLabel} selecionados`;
  const toggle = (id: string) => onChange(selectedIds.includes(id) ? selectedIds.filter((value) => value !== id) : [...selectedIds, id]);
  const selectVisible = () => onChange(Array.from(new Set([...selectedIds, ...filtered.map((account) => account.id)])));
  return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button variant="outline" className={cn("gd-filter-control gd-filter-account min-h-11 w-full justify-between bg-card font-normal sm:h-10 sm:min-h-0 sm:w-auto sm:min-w-[220px]", className)} aria-label={ariaLabel}><span className="flex min-w-0 items-center gap-2 truncate">{selectedIds.length > 0 && <Badge className="gd-account-count h-5 min-w-5 shrink-0 rounded-md border px-1.5 text-[10px] font-semibold">{selectedIds.length}</Badge>}<span className="truncate">{label}</span></span><ChevronDown className="h-4 w-4 shrink-0 opacity-60" /></Button></PopoverTrigger><PopoverContent className={cn("w-[380px] max-w-[calc(100vw-2rem)] p-0", popoverClassName)} align="start"><div className="border-b bg-popover p-2"><div className="relative"><Search className="absolute left-2 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" /><Input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder={searchPlaceholder} className="h-9 pl-7 pr-7" />{search && <button type="button" onClick={() => setSearch("")} className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground" aria-label="Limpar busca"><X className="h-3.5 w-3.5" /></button>}</div><div className="flex items-center justify-between px-1 pt-2 text-xs"><button type="button" onMouseDown={(event) => event.preventDefault()} onClick={() => onChange([])} className="text-muted-foreground hover:underline">{emptyLabel}</button><button type="button" onMouseDown={(event) => event.preventDefault()} onClick={selectVisible} className="text-primary hover:underline" disabled={!filtered.length}>Selecionar visíveis ({filtered.length})</button></div></div><ScrollArea className="h-[280px]"><div className="p-1">{filtered.map((account) => { const checked = selectedIds.includes(account.id); return <button key={account.id} type="button" onMouseDown={(event) => event.preventDefault()} onClick={() => toggle(account.id)} className={cn("flex w-full items-start gap-2 rounded px-2 py-2 text-left text-sm transition hover:bg-accent", checked && "bg-accent/50")}><span className={cn("mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded border", checked ? "border-primary bg-primary text-primary-foreground" : "border-muted-foreground/40")}>{checked && <Check className="h-3 w-3" />}</span><span className="min-w-0 flex-1 break-words leading-snug">{account.name}</span></button>; })}{!filtered.length && <div className="px-3 py-6 text-center text-sm text-muted-foreground">Nenhuma conta encontrada.</div>}</div></ScrollArea></PopoverContent></Popover>;
}
