import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, CheckCircle2, CircleAlert, CircleDollarSign, RefreshCw, Trophy, Users, WalletCards } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useGlobalFilters } from "@/contexts/GlobalFiltersContext";
import { useExpertOperations } from "@/hooks/useExpertOperations";
import { useAdAccounts } from "@/hooks/useAdAccounts";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";

const brl = (cents: number | null | undefined) => cents == null ? "Indisponível" : (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const dateLabel = (value: string | null | undefined) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR") : "—";

function ParticipantRows({ rows, type }: { rows: any[]; type: "student" | "model_patient" }) {
  const scoped = rows.filter((row) => row.participant_type === type).slice(0, 10);
  return <div className="space-y-1.5">{Array.from({ length: 10 }, (_, index) => { const row = scoped[index]; return <div key={`${type}-${index}`} className="grid grid-cols-[24px_minmax(0,1fr)_auto] items-center gap-2 rounded-lg border border-border/60 bg-background/30 px-2.5 py-2 text-xs"><span className="text-muted-foreground">{index + 1}</span><div className="min-w-0 truncate"><span className={row ? "font-semibold" : "text-muted-foreground"}>{row?.name || "Vaga disponível"}</span>{row?.seller_name && <span className="ml-1 text-[10px] text-muted-foreground">· {row.seller_name}</span>}</div><span className={row ? "font-semibold text-primary" : "text-muted-foreground"}>{row ? brl(row.cash_received_cents) : "—"}</span></div>; })}</div>;
}

function ClassCard({ eventClass, sales }: { eventClass: any; sales: any[] }) {
  const classSales = sales.filter((row) => row.event_class_id === eventClass.id || (row.class_name && row.class_name.toLocaleLowerCase() === String(eventClass.title).toLocaleLowerCase()));
  const students = classSales.filter((row) => row.participant_type === "student");
  const patients = classSales.filter((row) => row.participant_type === "model_patient");
  const capacity = Number(eventClass.max_students || eventClass.max_people || 10);
  const occupancy = capacity ? Math.min(students.length / capacity * 100, 100) : 0;
  const revenue = classSales.reduce((sum, row) => sum + Number(row.gross_amount_cents || 0), 0);
  const cash = classSales.reduce((sum, row) => sum + Number(row.cash_received_cents || 0), 0);
  const statusLabel = eventClass.status === "sold_out" ? "Esgotada" : eventClass.status === "finished" ? "Finalizada" : eventClass.status === "cancelled" ? "Cancelada" : eventClass.status === "upcoming" ? "Em breve" : "Aberta";
  return <Card className="min-w-[min(92vw,520px)] max-w-[520px] shrink-0 overflow-hidden border-border/80 bg-card/95 shadow-lg"><CardHeader className="space-y-3 pb-3"><div className="flex items-start justify-between gap-3"><div><Badge variant={eventClass.status === "cancelled" ? "destructive" : eventClass.status === "sold_out" ? "secondary" : "default"}>{statusLabel}</Badge><CardTitle className="mt-2 text-lg">{eventClass.title}</CardTitle><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="h-3.5 w-3.5" />{dateLabel(eventClass.date_start)}{eventClass.date_end ? ` – ${dateLabel(eventClass.date_end)}` : ""}{eventClass.location ? ` · ${eventClass.location}` : ""}</p></div><div className="text-right text-xs text-muted-foreground"><div>{students.length}/{capacity} alunas</div><Progress value={occupancy} className="mt-2 h-2 w-24" /></div></div><div className="grid grid-cols-2 gap-2"><div className="rounded-lg border border-border/60 bg-background/35 p-2"><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Faturamento</div><div className="mt-1 font-bold text-primary">{brl(revenue)}</div></div><div className="rounded-lg border border-border/60 bg-background/35 p-2"><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Caixa recebido</div><div className="mt-1 font-bold text-emerald-500">{brl(cash)}</div></div></div></CardHeader><CardContent className="space-y-4"><section><h4 className="mb-2 flex items-center gap-2 text-xs font-black uppercase tracking-wider"><Users className="h-3.5 w-3.5 text-primary" />Alunas</h4><ParticipantRows rows={students} type="student" /></section><section><h4 className="mb-2 flex items-center gap-2 text-xs font-black uppercase tracking-wider"><Users className="h-3.5 w-3.5 text-fuchsia-500" />Pacientes-modelo</h4><ParticipantRows rows={patients} type="model_patient" /></section></CardContent></Card>;
}

export function ExpertOperationsView() {
  const { startDate, endDate } = useGlobalFilters();
  const experts = useQuery({ queryKey: ["expert-operations-experts"], queryFn: async () => { const { data, error } = await (supabase as any).from("experts").select("id,nome").eq("ativo", true).order("nome"); if (error) throw error; return data || []; } });
  const [expertId, setExpertId] = useState("");
  const selectedExpertId = expertId || experts.data?.[0]?.id;
  const operations = useExpertOperations(selectedExpertId);
  const accounts = useAdAccounts();
  const [slide, setSlide] = useState(0);
  const visibleClasses = useMemo(() => operations.classes.slice(slide, slide + 3), [operations.classes, slide]);
  const gross = operations.sales.reduce((sum, row) => sum + Number(row.gross_amount_cents || 0), 0);
  const cash = operations.sales.reduce((sum, row) => sum + Number(row.cash_received_cents || 0), 0);
  const conversion = operations.traffic.totalLeads ? operations.sales.length / operations.traffic.totalLeads * 100 : null;
  const [accountId, setAccountId] = useState("");
  const [studentSheet, setStudentSheet] = useState("");
  const [patientSheet, setPatientSheet] = useState("");
  const saveConfig = async () => {
    if (!selectedExpertId) return;
    if (accountId) await (supabase as any).from("expert_operation_sources").upsert({ expert_id: selectedExpertId, ad_account_id: accountId, timezone: "America/Sao_Paulo", attribution_window: "account_default" }, { onConflict: "expert_id,ad_account_id" });
    const rows = [studentSheet.trim() ? { expert_id: selectedExpertId, participant_type: "student", spreadsheet_id: studentSheet.trim(), worksheet_name: "Alunas", status: "pending" } : null, patientSheet.trim() ? { expert_id: selectedExpertId, participant_type: "model_patient", spreadsheet_id: patientSheet.trim(), worksheet_name: "Pacientes-modelo", status: "pending" } : null].filter(Boolean);
    for (const row of rows) {
      const { data } = await (supabase as any).from("expert_sheet_connections").upsert(row, { onConflict: "expert_id,participant_type" }).select("id").single();
      if (data?.id) await supabase.functions.invoke("google-sheets-sync", { body: { connection_id: data.id } });
    }
    void operations.refetch();
  };
  return <div className="space-y-5"><div className="flex flex-col gap-3 rounded-2xl border border-primary/20 bg-primary/[.04] p-4 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-primary"><Trophy className="h-3.5 w-3.5" />Operação do Expert</div><h2 className="mt-1 text-xl font-black">Turmas, tráfego e comercial</h2><p className="mt-1 text-xs text-muted-foreground">{startDate.toLocaleDateString("pt-BR")} a {endDate.toLocaleDateString("pt-BR")} · fonte de vendas: Google Sheets</p></div><Select value={selectedExpertId || ""} onValueChange={setExpertId}><SelectTrigger className="w-full lg:w-64"><SelectValue placeholder="Selecione o expert" /></SelectTrigger><SelectContent>{(experts.data || []).map((expert: any) => <SelectItem key={expert.id} value={expert.id}>{expert.nome}</SelectItem>)}</SelectContent></Select><div className="flex items-center gap-2 text-xs"><span className={`h-2 w-2 rounded-full ${operations.sync.status === "fresh" ? "bg-emerald-500" : operations.sync.status === "syncing" ? "bg-amber-500" : "bg-red-500"}`} />{operations.sync.status === "fresh" ? "Dados atualizados" : operations.sync.status === "syncing" ? "Sincronizando" : "Dados pendentes"}</div><Button variant="outline" size="sm" onClick={() => operations.refetch()}><RefreshCw className="mr-2 h-3.5 w-3.5" />Atualizar</Button></div>
    <section className="space-y-3"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-muted-foreground">Calendário operacional</p><h3 className="text-lg font-black">Turmas</h3></div><div className="flex gap-1"><Button size="icon" variant="outline" aria-label="Turmas anteriores" disabled={slide === 0} onClick={() => setSlide((value) => Math.max(0, value - 1))}><ArrowLeft className="h-4 w-4" /></Button><Button size="icon" variant="outline" aria-label="Próximas turmas" disabled={slide + 3 >= operations.classes.length} onClick={() => setSlide((value) => Math.min(Math.max(operations.classes.length - 3, 0), value + 1))}><ArrowRight className="h-4 w-4" /></Button></div></div><div className="flex gap-4 overflow-x-auto pb-3 snap-x">{visibleClasses.length ? visibleClasses.map((eventClass: any) => <div className="snap-start" key={eventClass.id}><ClassCard eventClass={eventClass} sales={operations.sales} /></div>) : <Card className="w-full border-dashed"><CardContent className="flex items-center gap-3 p-8 text-sm text-muted-foreground"><CircleAlert className="h-5 w-5" />Nenhuma turma encontrada para este expert.</CardContent></Card>}</div></section>
    <section className="space-y-3"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-muted-foreground">Aquisição e retorno</p><h3 className="text-lg font-black">Tráfego pago</h3></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Investimento", operations.traffic.spend == null ? "Indisponível" : brl(Math.round(operations.traffic.spend * 100))], ["Leads Meta", operations.traffic.totalLeads ?? "Indisponível"], ["CPL", operations.traffic.cpl == null ? "Indisponível" : brl(Math.round(operations.traffic.cpl * 100))], ["Vendas", operations.sales.length], ["Conversão", conversion == null ? "Indisponível" : `${conversion.toFixed(1)}%`]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><div className="text-[10px] font-black uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-2 text-xl font-black">{value}</div></CardContent></Card>)}</div></section>
    <section className="space-y-3"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-muted-foreground">Performance comercial</p><h3 className="text-lg font-black">Ranking de vendedores</h3></div><Card><CardContent className="p-0">{operations.sellers.length ? operations.sellers.map((seller, index) => <div key={seller.name} className="grid gap-3 border-b border-border p-4 last:border-b-0 md:grid-cols-[40px_minmax(0,1fr)_120px_120px] md:items-center"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 font-black text-primary">{index + 1}</div><div><div className="font-bold">{seller.name}</div><div className="mt-1 flex items-center gap-2 text-xs text-muted-foreground"><Progress value={seller.progress} className="h-1.5 max-w-44" />{seller.goal ? `${seller.progress.toFixed(0)}% da meta` : "Meta não configurada"}</div></div><div className="text-sm"><div className="font-bold">{brl(seller.grossRevenue)}</div><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Bruto</div></div><div className="text-sm"><div className="font-bold text-emerald-500">{brl(seller.cashReceived)}</div><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Caixa real</div></div></div>) : <div className="p-8 text-center text-sm text-muted-foreground">Aguardando vendas importadas das planilhas.</div>}</CardContent></Card><div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><CircleDollarSign className="h-4 w-4 text-primary" /><div className="mt-2 text-[10px] font-black uppercase tracking-wider text-muted-foreground">Faturamento bruto</div><div className="mt-1 text-lg font-black">{brl(gross)}</div></CardContent></Card><Card><CardContent className="p-4"><WalletCards className="h-4 w-4 text-emerald-500" /><div className="mt-2 text-[10px] font-black uppercase tracking-wider text-muted-foreground">Caixa real</div><div className="mt-1 text-lg font-black text-emerald-500">{brl(cash)}</div></CardContent></Card><Card><CardContent className="p-4"><CheckCircle2 className="h-4 w-4 text-primary" /><div className="mt-2 text-[10px] font-black uppercase tracking-wider text-muted-foreground">Margem disponível</div><div className="mt-1 text-lg font-black">Indisponível</div></CardContent></Card></div></section>
    {operations.sync.errors.length > 0 && <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-700 dark:text-amber-300">Dados parciais: {operations.sync.errors.join(" · ")}</div>}
    <Card><CardHeader><CardTitle className="text-base">Fontes deste expert</CardTitle><p className="text-xs text-muted-foreground">Vincule contas Meta e as duas planilhas padrão. O token Google permanece no backend.</p></CardHeader><CardContent className="grid gap-4 md:grid-cols-4"><Select value={accountId} onValueChange={setAccountId}><SelectTrigger><SelectValue placeholder="Conta Meta" /></SelectTrigger><SelectContent>{(accounts.data || []).map((account: any) => <SelectItem key={account.id} value={account.id}>{account.name}</SelectItem>)}</SelectContent></Select><Input value={studentSheet} onChange={(event) => setStudentSheet(event.target.value)} placeholder="ID da planilha · Alunas" aria-label="ID da planilha de alunas" /><Input value={patientSheet} onChange={(event) => setPatientSheet(event.target.value)} placeholder="ID da planilha · Pacientes-modelo" aria-label="ID da planilha de pacientes-modelo" /><Button onClick={() => void saveConfig()} disabled={!selectedExpertId}>Salvar fontes</Button></CardContent></Card>
  </div>;
}
